export const list = [
  {
    id: 1,
    name: "Ani Samuel",
    location: "Aba Centre",
    leave: false,
    fileNo: 200,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/men/54.jpg",
  },
  {
    id: 2,
    name: "Abdul Suleiman",
    location: "Kaduna Centre",
    leave: false,
    fileNo: 300,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/men/59.jpg",
  },
  {
    id: 3,
    name: "Bolarinde Shola",
    location: "Aba Centre",
    leave: false,
    fileNo: 400,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/men/80.jpg",
  },
  {
    id: 4,
    name: "Chukwu Matthew",
    location: "Enugu Centre",
    leave: true,
    fileNo: 100,
    gl: 14,
    step: 4,
    rank: "CFVCO",
    lastP: "Jan 01, 2021",
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 5,
    name: "Funmi Egbeda",
    location: "Akure Centre",
    leave: false,
    fileNo: 500,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
  },
  {
    id: 6,
    name: "Nasiru Abdulmalik",
    location: "Jigawa Centre",
    leave: false,
    fileNo: 600,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    id: 7,
    name: "Chijioke Asogwa",
    location: "Enugu Centre",
    leave: false,
    fileNo: 700,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    id: 8,
    name: "Mba Ekene",
    location: "Head Office",
    leave: false,
    fileNo: 800,
    gl: 12,
    step: 4,
    rank: "PFVCO",
    lastP: "Jan 01, 2023",
    avatar: "https://randomuser.me/api/portraits/women/88.jpg",
  },
  {
    id: 9,
    name: "Mary Mary",
    location: "Head Office",
    leave: false,
    fileNo: 900,
    gl: 12,
    step: 4,
    rank: "PFVCO",
    lastP: "Jan 01, 2023",
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
  },
  {
    id: 10,
    name: "Maxwell Egbo",
    location: "SEZO, Onitsha",
    leave: true,
    fileNo: 950,
    gl: 10,
    step: 4,
    rank: "SFVCO",
    lastP: "Jan 01, 2022",
    avatar: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    id: 11,
    name: "Ray Ekene",
    location: "SEZO, Onitsha",
    leave: false,
    fileNo: 250,
    gl: 13,
    step: 7,
    rank: "ACFVCO",
    lastP: "Jan 01, 2020",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
  },
];
